CREATE SCHEMA IF NOT EXISTS gp;

CREATE TABLE IF NOT EXISTS gp.GAME (
  ID BIGINT PRIMARY KEY auto_increment,
  TITLE VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(100) NOT NULL ,
  PLATFORM VARCHAR(20) ,
  RELEASE_DATE DATE
);


CREATE TABLE IF NOT EXISTS gp.GAME_REVIEW (
    ID BIGINT PRIMARY KEY auto_increment,
    GAME_ID BIGINT,
    REVIEWER VARCHAR(30),
    REVIEW_DATE DATE,
    REVIEW VARCHAR(200)
)